/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Launcher */

#ifndef _Included_Launcher
#define _Included_Launcher
#ifdef __cplusplus
extern "C" {
#endif
#undef Launcher_FOCUS_TRAVERSABLE_UNKNOWN
#define Launcher_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef Launcher_FOCUS_TRAVERSABLE_DEFAULT
#define Launcher_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef Launcher_FOCUS_TRAVERSABLE_SET
#define Launcher_FOCUS_TRAVERSABLE_SET 2L
#undef Launcher_TOP_ALIGNMENT
#define Launcher_TOP_ALIGNMENT 0.0f
#undef Launcher_CENTER_ALIGNMENT
#define Launcher_CENTER_ALIGNMENT 0.5f
#undef Launcher_BOTTOM_ALIGNMENT
#define Launcher_BOTTOM_ALIGNMENT 1.0f
#undef Launcher_LEFT_ALIGNMENT
#define Launcher_LEFT_ALIGNMENT 0.0f
#undef Launcher_RIGHT_ALIGNMENT
#define Launcher_RIGHT_ALIGNMENT 1.0f
#undef Launcher_serialVersionUID
#define Launcher_serialVersionUID -7644114512714619750i64
#undef Launcher_serialVersionUID
#define Launcher_serialVersionUID 4613797578919906343i64
#undef Launcher_INCLUDE_SELF
#define Launcher_INCLUDE_SELF 1L
#undef Launcher_SEARCH_HEAVYWEIGHTS
#define Launcher_SEARCH_HEAVYWEIGHTS 1L
#undef Launcher_serialVersionUID
#define Launcher_serialVersionUID -2728009084054400034i64
#undef Launcher_serialVersionUID
#define Launcher_serialVersionUID -5836846270535785031i64
#undef Launcher_serialVersionUID
#define Launcher_serialVersionUID 5121819178012096909i64
#undef Launcher_READ_BUFFER_SIZE
#define Launcher_READ_BUFFER_SIZE 1000L
/*
 * Class:     Launcher
 * Method:    WebMain
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Launcher_WebMain
  (JNIEnv *, jobject);

/*
 * Class:     Launcher
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Launcher_initialise
  (JNIEnv *, jobject);

/*
 * Class:     Launcher
 * Method:    update
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_Launcher_update
  (JNIEnv *, jobject);

/*
 * Class:     Launcher
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Launcher_shutdown
  (JNIEnv *, jobject);

/*
 * Class:     Launcher
 * Method:    setCanvas
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_Launcher_setCanvas
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     Launcher
 * Method:    setResourcePath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Launcher_setResourcePath
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
