def configure(conf):
    pass


def build(bld):
    # Add source files
    files = []
    files.extend(bld.path.ant_glob("*.cpp"))

    # Bulid OpenGL renderer Plugin
    bld.shlib(
        source=files,
        target="../../Debug/Renderer_ogl",
        name="Renderer_ogl",
        # includes     = ['../../Libs/SDL/include'],
        cxxflags=['-fpermissive', '-fPIC'],
        use=['kge-0.1', 'GLEW', 'SDL2'],
        lib=['Cg', 'CgGL']
    )
