libs = ['SDL2', 'IL']
src = Glob('*.cpp')
Export('src')
SConscript([  'core/SConscript'
            , 'en/SConscript'
            , 'gfx/SConscript'
            , 'io/SConscript'
            , 'math/SConscript'
            , 'sn/SConscript'])
SharedLibrary('kge', src, LIBS=libs, CPPPATH='../include/kge',
    LIBPATH = '#Libs')