Kochol Game Engine: kge::gfx Namespace Reference
kge::gfx Namespace Reference
Graphics classes.
Classes
struct AnimationData
class Animation
class CMatPhong
class CMatTree
Custom material for trees.
class Color
Color class.
class Colorf
In class rang ba 4 float hast.
class CustomMaterial
Custom material base class.
class SimpleLightingCM
Simple lighting.
class DynamicHardwareBuffer
Dynamic buffer for working with buffer witch to need change many times before rendering.
class HardwareBuffer
class Image
class ImageData
The image resource class.
class Lighting
In class interface asli kar ba nor ha hast.
class Material
class MaterialManager
class MaterialParams
class MeshManager
This class is for working with meshes and changing their vertex.
class Renderer
The Renderer interface has functions to work with graphics card.
class Shader
This class is for using shaders.
class ShaderInstance
struct Vertex2
struct Vertex3
3D Vertex
struct Vertex3C
3D Vertex with color
struct Vertex3T
3D Vertex with One texture.
struct Vertex3CT
3D Vertex with color and texture coordinate.
struct Vertex3TN
3D Vertex with one texture and normal vector.
struct Vertex3TTN
3D Vertex with two texcoord and normal vector.
struct Vertex3TNC
3D vertex with texture, normal and color.
struct VertexNTC
Normal, texture and color.
struct Vertex3I
3D vertex with Bone ID
struct TextureInfo
Etelate marbot be texture haye load shode ke tavasote SceneManager zakhire mishe.
struct LightData
Light structure.
struct KeyFrame
struct Joint
class Texture
class Tile
This class store tiles data for TileTexture class.
class TileTexture
class VertexDec
Custom vertex declaration.
struct CustomVertexElement
Use an array of CustomVertexElement to create custom vertices.
Typedefs
typedef void(* kgeRenderCallback)(KgeUnknown *Sender)
standard callback function
typedef char * ShaderHandle
A handler for shader constant that you can change them with this handler.
typedef void * CustomVertex
Custom vertex pointer.
Enumerations
enum RendererAPI { ERA_DirectX9, ERA_OpenGL }
Renderer API type.
enum AntiAliasingMode { EAAM_Off, EAAM_MSAA }
enum TextureFormat {
ETF_NONE = 0, ETF_A32B32G32R32F, ETF_R32F, ETF_R16G16F,
ETF_A8R8G8B8, ETF_A8B8G8R8, ETF_X8R8G8B8, ETF_X8B8G8R8,
ETF_A8L8, ETF_A8, ETF_DXT1, ETF_DXT2,
ETF_DXT3, ETF_DXT4, ETF_DXT5, ETF_NULL
}
Texture formats.
enum CustomMaterialType { ECMT_Unknown, ECMT_Lighting, ECMT_Tree, ECMT_PhongLighting }
enum VertexShaderEntry { EVSE_Unknown = 0, EVSE_GetVertexShaderHandles, EVSE_ChangePosition, EVSE_Lighting }
enum PixelShaderEntry { EPSE_Start = 0, EPSE_Lighting, EPSE_GetPixelShaderHandles }
enum HardwareBufferType { EHBT_VertexBuffer = 0, EHBT_IndexBuffer }
Hardware buffers types.
enum IndexBufferType { EIBT_16Bit = 0, EIBT_32Bit }
Index Buffer type 16 bit or 32 bit.
enum ImageFormat {
EIF_RGB, EIF_RGBA, EIF_BGR, EIF_BGRA,
EIF_A
}
The image formats.
enum LightingType { ELIT_UnLit, ELIT_Simple, ELIT_Phong, ELIT_Custom }
enum LightingMode { ELM_Unknown, ELM_PerVertex, ELM_PerPixel }
enum CustomMaterialOrder { ECMO_AtBeginning, ECMO_AtEnd, ECMO_Count }
enum ParamUsage {
EPU_Position, EPU_Texcoord, EPU_Normal, EPU_Color,
EPU_Tangent, EPU_BiNormal, EPU_Count
}
enum ParamType {
EPT_Float, EPT_Float2, EPT_Float3, EPT_Float4,
EPT_Float3x3, EPT_Float4x4, EPT_Int, EPT_Int2,
EPT_Int3, EPT_Int4, EPT_Count
}
enum TransformMode { ETM_World, ETM_View, ETM_Projection, ETM_ViewProjection }
Noe matrixi ke mikhahid taghir bedid.
enum RenderFlags {
ERF_2D = 0, ERF_Lighting, ERF_AlphaBlending, ERF_AdditiveBlending,
ERF_AlphaTest, ERF_StencilBuffer, ERF_DepthBuffer, ERF_ZWrite,
ERF_VSync, ERF_WireFrame, ERF_Culling, ERF_ColorRendering,
ERF_Scissor, ERF_Count
}
Khasiat haye engine ke baraye render estefade mishe.
enum TextureParams {
ETP_Point = 0, ETP_Linear, ETP_Anisotropic, ETP_Wrap,
ETP_BorderColor, ETP_Clamp, ETP_Mirror
}
Anvae tanzim ha baraye Texture ha.
enum GraphicCardCaps {
EGCC_VertexShader1_1, EGCC_FragmentShader1_1, EGCC_FragmentShader1_4, EGCC_VertexShader2,
EGCC_FragmentShader2, EGCC_VertexShader3, EGCC_FragmentShader3, EGCC_ShaderObject,
EGCC_GeometryShader4, EGCC_ShaderModel4, EGCC_ShaderModel3, EGCC_ShaderModel2,
EGCC_OpenGL2, EGCC_OpenGL3, EGCC_OpenGL4, EGCC_DXT1,
EGCC_DXT3, EGCC_DXT5, EGCC_INTZ, EGCC_Count
}
Ghabeliat haye cart graphic.
enum ShaderVersion {
ESV_VS1_1, ESV_VS2, ESV_VS3, ESV_PS1_1,
ESV_PS1_4, ESV_PS2, ESV_PS3
}
Shader versions.
enum CullMode { ECM_None, ECM_CCW, ECM_CW }
enum RendererPipeline { ERP_Forward, ERP_Deferred }
enum DepthTestMode { EDTM_LessEqual, EDTM_Greater }
enum VertexType {
EVT_V2 = 0, EVT_V3, EVT_V3C, EVT_V3T,
EVT_V3CT, EVT_V3TN, EVT_V3TNC, EVT_V3TTN,
EVT_P0NT1BT2I3, EVT_P0NTC1BT2, EVT_PJ0NT1BT2I3, EVT_Count
}
The Vertex Type.
enum LightType { ELT_Directional, ELT_Point, ELT_Spot }
Light Type.
enum FogType { EFT_NONE, EFT_LINEAR, EFT_EXP, EFT_EXP2 }
Fog type.
enum CompressType { ECT_None, ECT_DXT1, ECT_DXT3, ECT_DXT5 }
enum TileType { ETT_BackTile = 0, ETT_FrontTile }
The tile type. currently we have two tile type one for back tiles and one for front tile.
enum VertexElementType {
EVET_Float1 = 0, EVET_Float2 = 1, EVET_Float3 = 2, EVET_Float4 = 3,
EVET_Color = 4, EVET_UByte4 = 5, EVET_Short2 = 6, EVET_Short4 = 7,
EVET_UByte4N = 8, EVET_Short2N = 9, EVET_Short4N = 10, EVET_UShort2N = 11,
EVET_UShort4N = 12, EVET_UDec3 = 13, EVET_Dec3N = 14, EVET_Float16_2 = 15,
EVET_Float16_4 = 16, EVET_Unused = 17
}
Vertex Element Type enum.
enum VertexElementMethod {
EVEM_Default = 0, EVEM_PartialU = 1, EVEM_PartialV = 2, EVEM_CrossUV = 3,
EVEM_UV = 4, EVEM_LookUp = 5, EVEM_LookUpPreSampled = 6
}
Vertex Element Method enum.
enum VertexElementUsage {
EVEU_Position = 0, EVEU_BlendWeight, EVEU_BlendIndices, EVEU_Normal,
EVEU_PSize, EVEU_TexCoord, EVEU_Tangent, EVEU_Binormal,
EVEU_TessFactor, EVEU_PositionT, EVEU_Color, EVEU_Fog,
EVEU_Depth, EVEU_Sample
}
Vertex Element Usage enum.
enum ImageType { E_IT_UnKnown, E_IT_BMP, E_IT_JPEG }
Noe imagei ke mikhahid load shavad.
Functions
int GetKey (float fTime, const kge::gfx::KeyFrame *p, int num)
template<class VType >
void RecalculateNormals_Smooth (VType *verts, u32 numVerts, u16 *idx, u32 numIdx)
Recalculate the normals.
template<class VposType , class VnorType >
void RecalculateNormals_Smooth (VposType *pos, VnorType *normals, u32 numVerts, u16 *idx, u32 numIdx)
Recalculate the normals.
template<class VnorType >
void RecalculateNormals_Smooth (Vertex3 *pos, VnorType *normals, u32 numVerts, u16 *idx, u32 numIdx)
Recalculate the normals.
template<class VnorType >
void RecalculateNormals_Smooth32 (Vertex3 *pos, VnorType *normals, u32 numVerts, u32 *idx, u32 numIdx)
Recalculate the normals.
void RecalculateNormals_Smooth (Vertex3 *pos, Vertex3T *NorTex, u32 numVerts, u16 *idx, u32 numIdx)
Recalculate the normals.
template<class VType >
void RecalculateNormals_Flat (VType *verts, u32 numVerts, u16 *idx, u32 numIdx)
Recalculate the normals.
template<class VType >
void CalcBinormalsTangents (VType *verts, Vertex3 *TangentBinormal, u32 numVerts, u16 *idx, u32 numIdx)
Calculate Binormal & Tangent.
template<class VType >
void CalcBinormalsTangents32 (VType *verts, Vertex3 *TangentBinormal, u32 numVerts, u32 *idx, u32 numIdx)
Calculate Binormal & Tangent.
void CalcTangent (Vertex3 &normal, Vertex3 &tangent, Vertex3 &binormal, Vertex3 &vt1, Vertex3 &vt2, Vertex3 &vt3, Vertex2 &tc1, Vertex2 &tc2, Vertex2 &tc3)
void CalcBinormalsTangents (Vertex3 *Pos, Vertex3T *NorTex, Vertex3 *TangentBinormal, u32 numVerts, u16 *idx, u32 numIdx)
Calculate Binormal & Tangent.
void CalcBinormalsTangents32 (Vertex3 *Pos, Vertex3T *NorTex, Vertex3 *TangentBinormal, u32 numVerts, u32 *idx, u32 numIdx)
Calculate Binormal & Tangent.
void CalcBinormalsTangents (Vertex3 *Pos, VertexNTC *NorTex, Vertex3 *TangentBinormal, u32 numVerts, u16 *idx, u32 numIdx)
Calculate Binormal & Tangent.
void CalcBinormalsTangents32 (Vertex3 *Pos, VertexNTC *NorTex, Vertex3 *TangentBinormal, u32 numVerts, u32 *idx, u32 numIdx)
Calculate Binormal & Tangent.
Variables
static const char * TextureFormatName []
Texture formats name.
static const char * ParamUsageNames []
static const char * ParamTypeNames []
struct kge::gfx::KeyFrame PACK_STRUCT
Detailed Description
Graphics classes.
Typedef Documentation
typedef void* kge::gfx::CustomVertex
Custom vertex pointer.
Definition at line 17 of file VertexDec.h.
typedef void(* kge::gfx::kgeRenderCallback)(KgeUnknown *Sender)
standard callback function
Definition at line 139 of file Renderer.h.
typedef char* kge::gfx::ShaderHandle
A handler for shader constant that you can change them with this handler.
Definition at line 25 of file Shader.h.
Enumeration Type Documentation
enum kge::gfx::AntiAliasingMode
Enumerator:
EAAM_Off
EAAM_MSAA
Definition at line 16 of file enums.h.
enum kge::gfx::CompressType
Enumerator:
ECT_None
Don't use any compression
ECT_DXT1
Use DXT1 compress format
ECT_DXT3
Use DXT3 compress format
ECT_DXT5
Use DXT5 compress format
Definition at line 18 of file Texture.h.
enum kge::gfx::CullMode
Enumerator:
ECM_None
ECM_CCW
ECM_CW
Definition at line 119 of file Renderer.h.
enum kge::gfx::CustomMaterialOrder
Enumerator:
ECMO_AtBeginning
ECMO_AtEnd
ECMO_Count
Definition at line 41 of file MaterialParams.h.
enum kge::gfx::CustomMaterialType
Enumerator:
ECMT_Unknown
ECMT_Lighting
ECMT_Tree
ECMT_PhongLighting
Definition at line 19 of file CustomMaterial.h.
enum kge::gfx::DepthTestMode
Enumerator:
EDTM_LessEqual
EDTM_Greater
Definition at line 132 of file Renderer.h.
enum kge::gfx::FogType
Fog type.
Enumerator:
EFT_NONE
EFT_LINEAR
EFT_EXP
EFT_EXP2
Definition at line 284 of file Structs.h.
enum kge::gfx::GraphicCardCaps
Ghabeliat haye cart graphic.
Enumerator:
EGCC_VertexShader1_1
Vertex Shader 1.1
EGCC_FragmentShader1_1
Fragment/Pixel Shader 1.1
EGCC_FragmentShader1_4
Fragment/Pixel Shader 1.4
EGCC_VertexShader2
Vertex Shader 2
EGCC_FragmentShader2
Fragment/Pixel Shader 2
EGCC_VertexShader3
Vertex Shader 3
EGCC_FragmentShader3
Fragment/Pixel Shader 3
EGCC_ShaderObject
Shader object
EGCC_GeometryShader4
Geometry shaders 4
EGCC_ShaderModel4
Shader model 4
EGCC_ShaderModel3
Shader model 3
EGCC_ShaderModel2
Shader model 2
EGCC_OpenGL2
OpenGL version 2.x
EGCC_OpenGL3
OpenGL version 3.x
EGCC_OpenGL4
OpenGL version 4.x
EGCC_DXT1
Can device support DXT1 compression texture type.
EGCC_DXT3
Can device support DXT3 compression texture type.
EGCC_DXT5
Can device support DXT5 compression texture type.
EGCC_INTZ
INTZ allows a 24-bit depth buffer previously used for rendering to be bound as a texture
EGCC_Count
Don't use it
Definition at line 81 of file Renderer.h.
enum kge::gfx::HardwareBufferType
Hardware buffers types.
Enumerator:
EHBT_VertexBuffer
EHBT_IndexBuffer
Definition at line 16 of file HardwareBuffer.h.
enum kge::gfx::ImageFormat
The image formats.
Enumerator:
EIF_RGB
EIF_RGBA
EIF_BGR
EIF_BGRA
EIF_A
Definition at line 17 of file Image.h.
enum kge::gfx::ImageType
Noe imagei ke mikhahid load shavad.
Enumerator:
E_IT_UnKnown
E_IT_BMP
Agar ke mikhahid khode engine format tasvir ra peyda konad in meghdar ra benevisid(engine az roye pasvand format tasvir ra moshakhas mikonad.
E_IT_JPEG
BMP Image.
JPEG Image
Definition at line 30 of file SceneManager.h.
enum kge::gfx::IndexBufferType
Index Buffer type 16 bit or 32 bit.
Enumerator:
EIBT_16Bit
EIBT_32Bit
Definition at line 24 of file HardwareBuffer.h.
enum kge::gfx::LightingMode
Enumerator:
ELM_Unknown
ELM_PerVertex
ELM_PerPixel
Definition at line 33 of file MaterialParams.h.
enum kge::gfx::LightingType
Enumerator:
ELIT_UnLit
ELIT_Simple
ELIT_Phong
ELIT_Custom
Definition at line 24 of file MaterialParams.h.
enum kge::gfx::LightType
Light Type.
Enumerator:
ELT_Directional
Directional Light.
ELT_Point
Point Light.
ELT_Spot
Spot Light.
Definition at line 247 of file Structs.h.
enum kge::gfx::ParamType
Enumerator:
EPT_Float
EPT_Float2
EPT_Float3
EPT_Float4
EPT_Float3x3
EPT_Float4x4
EPT_Int
EPT_Int2
EPT_Int3
EPT_Int4
EPT_Count
Definition at line 71 of file MaterialParams.h.
enum kge::gfx::ParamUsage
Enumerator:
EPU_Position
EPU_Texcoord
EPU_Normal
EPU_Color
EPU_Tangent
EPU_BiNormal
EPU_Count
Definition at line 48 of file MaterialParams.h.
enum kge::gfx::PixelShaderEntry
Enumerator:
EPSE_Start
EPSE_Lighting
EPSE_GetPixelShaderHandles
Definition at line 36 of file CustomMaterial.h.
enum kge::gfx::RendererAPI
Renderer API type.
Enumerator:
ERA_DirectX9
ERA_OpenGL
Definition at line 9 of file enums.h.
enum kge::gfx::RendererPipeline
Enumerator:
ERP_Forward
ERP_Deferred
Definition at line 126 of file Renderer.h.
enum kge::gfx::RenderFlags
Khasiat haye engine ke baraye render estefade mishe.
Enumerator:
ERF_2D
ERF_Lighting
Dorbine 2 bodi.
ERF_AlphaBlending
Nor Pardazi.
ERF_AdditiveBlending
Alpha blending.
ERF_AlphaTest
Additive blending.
ERF_StencilBuffer
ERF_DepthBuffer
Stencil buffer for shadows and mirrors.
ERF_ZWrite
Z buffer.
ERF_VSync
Writing to the depth buffer.
ERF_WireFrame
VSync.
ERF_Culling
Wire frame view.
ERF_ColorRendering
Culling.
Rendering to color buffer
ERF_Scissor
Scissor.
ERF_Count
This is only for counting.
Definition at line 50 of file Renderer.h.
enum kge::gfx::ShaderVersion
Shader versions.
Enumerator:
ESV_VS1_1
Vertex Shader 1.1
ESV_VS2
Vertex Shader 2
ESV_VS3
Vertex Shader 3
ESV_PS1_1
Pixel Shader 1.1
ESV_PS1_4
Pixel Shader 1.4
ESV_PS2
Pixel Shader 2
ESV_PS3
Pixel Shader 3
Definition at line 107 of file Renderer.h.
enum kge::gfx::TextureFormat
Texture formats.
Enumerator:
ETF_NONE
ETF_A32B32G32R32F
ETF_R32F
ETF_R16G16F
ETF_A8R8G8B8
ETF_A8B8G8R8
ETF_X8R8G8B8
ETF_X8B8G8R8
ETF_A8L8
ETF_A8
ETF_DXT1
Use DXT1 compress format
ETF_DXT2
Use DXT2 compress format
ETF_DXT3
Use DXT3 compress format
ETF_DXT4
Use DXT4 compress format
ETF_DXT5
Use DXT5 compress format
ETF_NULL
The NULL texture format is useful when you only want depth buffer.
Definition at line 24 of file enums.h.
enum kge::gfx::TextureParams
Anvae tanzim ha baraye Texture ha.
Enumerator:
ETP_Point
ETP_Linear
Kamtarin Keifiyat bishtarin Sorat (Filtering).
ETP_Anisotropic
Keifiyate monaseb va sorate monesab baraye axar computer haye emroozi (Filtering).
ETP_Wrap
Behtarin keyfiyat kamtarin sorat (Filtering).
ETP_BorderColor
Texture baghale ham namayesh miyaband (Addressing).
ETP_Clamp
Border color (Addressing).
ETP_Mirror
Clamp Mode (Addressing).
Mirror mode (Addressing).
Definition at line 69 of file Renderer.h.
enum kge::gfx::TileType
The tile type. currently we have two tile type one for back tiles and one for front tile.
Enumerator:
ETT_BackTile
ETT_FrontTile
Definition at line 25 of file Tile.h.
enum kge::gfx::TransformMode
Noe matrixi ke mikhahid taghir bedid.
Enumerator:
ETM_World
ETM_View
World matrix.
ETM_Projection
View matrix.
ETM_ViewProjection
Projection matrix.
Definition at line 41 of file Renderer.h.
enum kge::gfx::VertexElementMethod
Vertex Element Method enum.
Enumerator:
EVEM_Default
EVEM_PartialU
EVEM_PartialV
EVEM_CrossUV
EVEM_UV
EVEM_LookUp
EVEM_LookUpPreSampled
Definition at line 51 of file VertexElement.h.
enum kge::gfx::VertexElementType
Vertex Element Type enum.
Enumerator:
EVET_Float1
EVET_Float2
EVET_Float3
EVET_Float4
EVET_Color
EVET_UByte4
EVET_Short2
EVET_Short4
EVET_UByte4N
EVET_Short2N
EVET_Short4N
EVET_UShort2N
EVET_UShort4N
EVET_UDec3
EVET_Dec3N
EVET_Float16_2
EVET_Float16_4
EVET_Unused
Definition at line 23 of file VertexElement.h.
enum kge::gfx::VertexElementUsage
Vertex Element Usage enum.
Enumerator:
EVEU_Position
EVEU_BlendWeight
EVEU_BlendIndices
EVEU_Normal
EVEU_PSize
EVEU_TexCoord
EVEU_Tangent
EVEU_Binormal
EVEU_TessFactor
EVEU_PositionT
EVEU_Color
EVEU_Fog
EVEU_Depth
EVEU_Sample
Definition at line 64 of file VertexElement.h.
enum kge::gfx::VertexShaderEntry
Enumerator:
EVSE_Unknown
EVSE_GetVertexShaderHandles
EVSE_ChangePosition
EVSE_Lighting
Definition at line 28 of file CustomMaterial.h.
enum kge::gfx::VertexType
The Vertex Type.
Enumerator:
EVT_V2
2D Vertex.
EVT_V3
3D Vertex.
EVT_V3C
3D Vertex with color.
EVT_V3T
3D Vertex with texture.
EVT_V3CT
3D Vertex with color and texture coordinate.
EVT_V3TN
3D Vertex with texture and normal vector.
EVT_V3TNC
3D Vertex with texture and normal vector and color.
EVT_V3TTN
3D Vertex with two texcoord and normal vector.
EVT_P0NT1BT2I3
Vertex3 + Normal vector + Texture coord + Tangent + Binormal in multi stream mode.
EVT_P0NTC1BT2
Vertex3 + Normal vector + Texture coord + Color + Tangent + Binormal in multi stream mode.
EVT_PJ0NT1BT2I3
Vertex3 + Joint index for hardware skinning + Normal vector + Texture coord + Tangent + Binormal + Instanced data in multi stream mode.
EVT_Count
For internal use
Definition at line 20 of file Structs.h.
Function Documentation
template<class VType > void kge::gfx::CalcBinormalsTangents (VType * verts, Vertex3 * TangentBinormal, u32 numVerts, u16 * idx, u32 numIdx)
Calculate Binormal & Tangent.
Definition at line 236 of file MeshManager.h.
References CalcTangent().
void kge::gfx::CalcBinormalsTangents (Vertex3 * Pos, Vertex3T * NorTex, Vertex3 * TangentBinormal, u32 numVerts, u16 * idx, u32 numIdx) inline
Calculate Binormal & Tangent.
Definition at line 361 of file MeshManager.h.
References CalcTangent().
void kge::gfx::CalcBinormalsTangents (Vertex3 * Pos, VertexNTC * NorTex, Vertex3 * TangentBinormal, u32 numVerts, u16 * idx, u32 numIdx) inline
Calculate Binormal & Tangent.
Definition at line 451 of file MeshManager.h.
References CalcTangent().
template<class VType > void kge::gfx::CalcBinormalsTangents32 (VType * verts, Vertex3 * TangentBinormal, u32 numVerts, u32 * idx, u32 numIdx)
Calculate Binormal & Tangent.
Definition at line 282 of file MeshManager.h.
References CalcTangent().
void kge::gfx::CalcBinormalsTangents32 (Vertex3 * Pos, Vertex3T * NorTex, Vertex3 * TangentBinormal, u32 numVerts, u32 * idx, u32 numIdx) inline
Calculate Binormal & Tangent.
Definition at line 406 of file MeshManager.h.
References CalcTangent().
void kge::gfx::CalcBinormalsTangents32 (Vertex3 * Pos, VertexNTC * NorTex, Vertex3 * TangentBinormal, u32 numVerts, u32 * idx, u32 numIdx) inline
Calculate Binormal & Tangent.
Definition at line 496 of file MeshManager.h.
References CalcTangent().
void kge::gfx::CalcTangent (Vertex3 & normal, Vertex3 & tangent, Vertex3 & binormal, Vertex3 & vt1, Vertex3 & vt2, Vertex3 & vt3, Vertex2 & tc1, Vertex2 & tc2, Vertex2 & tc3) inline
Definition at line 327 of file MeshManager.h.
References kge::math::Vector::Cross(), kge::gfx::Vertex3::Normalize(), kge::gfx::Vertex2::X, and kge::gfx::Vertex2::Y.
Referenced by CalcBinormalsTangents(), and CalcBinormalsTangents32().
int kge::gfx::GetKey (float fTime, const kge::gfx::KeyFrame * p, int num)
Referenced by kge::gfx::AnimationData::GetRotateKey(), and kge::gfx::AnimationData::GetTransKey().
template<class VType > void kge::gfx::RecalculateNormals_Flat (VType * verts, u32 numVerts, u16 * idx, u32 numIdx)
Recalculate the normals.
Definition at line 208 of file MeshManager.h.
References kge::math::Vector::Cross(), kge::math::Vector::Normalize(), kge::math::Vector::x, kge::math::Vector::y, and kge::math::Vector::z.
template<class VType > void kge::gfx::RecalculateNormals_Smooth (VType * verts, u32 numVerts, u16 * idx, u32 numIdx)
Recalculate the normals.
Definition at line 19 of file MeshManager.h.
References kge::math::Vector::Cross(), kge::math::Vector::Normalize(), kge::math::Vector::x, kge::math::Vector::y, and kge::math::Vector::z.
template<class VposType , class VnorType > void kge::gfx::RecalculateNormals_Smooth (VposType * pos, VnorType * normals, u32 numVerts, u16 * idx, u32 numIdx)
Recalculate the normals.
Definition at line 57 of file MeshManager.h.
References kge::math::Vector::Cross(), kge::math::Vector::Normalize(), kge::math::Vector::x, kge::math::Vector::y, and kge::math::Vector::z.
template<class VnorType > void kge::gfx::RecalculateNormals_Smooth (Vertex3 * pos, VnorType * normals, u32 numVerts, u16 * idx, u32 numIdx)
Recalculate the normals.
Definition at line 95 of file MeshManager.h.
References kge::math::Vector::Cross(), kge::math::Vector::Normalize(), kge::math::Vector::x, kge::math::Vector::y, and kge::math::Vector::z.
void kge::gfx::RecalculateNormals_Smooth (Vertex3 * pos, Vertex3T * NorTex, u32 numVerts, u16 * idx, u32 numIdx) inline
Recalculate the normals.
Definition at line 170 of file MeshManager.h.
References kge::math::Vector::Cross(), kge::math::Vector::Normalize(), kge::gfx::Vertex3::Normalize(), kge::gfx::Vertex3T::pos, kge::math::Vector::x, kge::gfx::Vertex3::X, kge::math::Vector::y, kge::gfx::Vertex3::Y, kge::math::Vector::z, and kge::gfx::Vertex3::Z.
template<class VnorType > void kge::gfx::RecalculateNormals_Smooth32 (Vertex3 * pos, VnorType * normals, u32 numVerts, u32 * idx, u32 numIdx)
Recalculate the normals.
Definition at line 133 of file MeshManager.h.
References kge::math::Vector::Cross(), kge::math::Vector::Normalize(), kge::math::Vector::x, kge::math::Vector::y, and kge::math::Vector::z.
Variable Documentation
struct kge::gfx::Joint kge::gfx::PACK_STRUCT
const char* kge::gfx::ParamTypeNames[] static
Initial value:
{
        "float",
        "float2",
        "float3",
        "float4",
        "float3x3",
        "float4x4",
        "int",
        "int2",
        "int3",
        "int4"
}
Definition at line 87 of file MaterialParams.h.
const char* kge::gfx::ParamUsageNames[] static
Initial value:
{
                "POSITION",
                "TEXCOORD",
                "NORMAL",
                "COLOR",
                "TANGENT",
                "BINORMAL"
}
Definition at line 61 of file MaterialParams.h.
const char* kge::gfx::TextureFormatName[] static
Initial value:
                {
                        "ETF_NONE",
                        "ETF_A32B32G32R32F",
                        "ETF_R32F",
                        "ETF_R16G16F",
                        "ETF_A8R8G8B8",
                        "ETF_A8B8G8R8",
                        "ETF_X8R8G8B8",
                        "ETF_X8B8G8R8",
                        "ETF_A8L8",
                        "ETF_A8",
                        "ETF_DXT1",
                        "ETF_DXT2",
                        "ETF_DXT3",
                        "ETF_DXT4",
                        "ETF_DXT5",
                        "ETF_NULL"
                }
Texture formats name.
Definition at line 46 of file enums.h.