Kochol Game Engine: kge::math::Ray Struct Reference
kge::math::Ray Struct Reference
#include <Ray.h>
Public Member Functions
void Set (const Vector &vPosition, const Vector &vTarget)
void CalcPickingRay (int x, int y, sn::Camera *pCam)
void TransformRayInverse (const Matrix *mat)
Public Attributes
Vector Position
Vector Target
Vector Direction
Detailed Description
Definition at line 17 of file Ray.h.
Member Function Documentation
void kge::math::Ray::CalcPickingRay (int x, int y, sn::Camera * pCam) inline
Definition at line 31 of file Ray.h.
References Direction, kge::sn::Camera::GetProjectionMatrix(), kge::sn::Camera::GetViewportHeight(), kge::sn::Camera::GetViewportWidth(), kge::math::Matrix::m_fMat, Position, kge::math::Vector::set(), and Target.
void kge::math::Ray::Set (const Vector & vPosition, const Vector & vTarget) inline
Definition at line 23 of file Ray.h.
References Direction, Position, and Target.
void kge::math::Ray::TransformRayInverse (const Matrix * mat) inline
Definition at line 50 of file Ray.h.
References Direction, kge::math::Matrix::Inverse(), Position, kge::math::Matrix::RotateVec(), Target, and kge::math::Matrix::TranslateVec().
Member Data Documentation
Vector kge::math::Ray::Direction
Definition at line 19 of file Ray.h.
Referenced by CalcPickingRay(), kge::math::Triangle::IntersectRay(), Set(), and TransformRayInverse().
Vector kge::math::Ray::Position
Definition at line 19 of file Ray.h.
Referenced by CalcPickingRay(), kge::math::Triangle::IntersectRay(), Set(), and TransformRayInverse().
Vector kge::math::Ray::Target
Definition at line 19 of file Ray.h.
Referenced by CalcPickingRay(), Set(), and TransformRayInverse().
The documentation for this struct was generated from the following file:
E:/mycodes/git/kge/Include/math/Ray.h